name: CI/CD Pipeline

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy dev-backend
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOSTNAME }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            cd /var/www/dev-olmat-backend
            git reset --hard
            git pull origin main
            yarn install
            yarn build
            pm2 stop dev-ecosystem.config.js
            pm2 start dev-ecosystem.config.js
